name: Android Manual Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      # 최신 안드로이드 빌드 툴러인 체인 검사를 우회하는 플래그를 추가했습니다.
      - name: Build APK
        run: flutter build apk --release --android-skip-build-dependency-validation
